import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Nav from "./nav";

export default function Home() {
  return (
    <>
      <Head>
        <title>Tor Henning Egenes - Web-utvikler</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;700&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <Nav />
      <main className="bg-gray-50 text-gray-900">
        <div className="container flex flex-col items-end border-b-2 border-gray-900">
          <h1 className="uppercase font-bold text-6xl md:text-8xl mb-3">
            Tor Henning Egenes
          </h1>
          <h2 className=" font-semibold text-4xl hover:bg-gray-900 hover:text-pink-600">
            Web developer
          </h2>
          <div>
            <button className="bg-gray-900 text-gray-50 px-16 py-2 hover:bg-pink-600 hover:text-gray-50 transition-colors duration-300 ease-out mr-5">
              About
            </button>
            <button className="bg-gray-900 text-gray-50 px-16 py-2 hover:bg-pink-600 hover:text-gray-50 transition-colors duration-300 ease-out">
              Projects
            </button>
          </div>
        </div>
        <article>
          <p>This is a article</p>
        </article>
      </main>

      <footer></footer>
    </>
  );
}
